from __future__ import annotations

import argparse
import getpass
import json
import os
import shutil
import stat
import subprocess
import urllib.error
import urllib.parse
import urllib.request
from pathlib import Path

from dotenv import dotenv_values

from .config import load_config

DEFAULT_STATE_DIR = Path("~/.local/share/pam-discord")
DISCORD_BOT_PERMISSIONS = (
    (1 << 4)  # manage channels
    | (1 << 10)  # view channels
    | (1 << 11)  # send messages
    | (1 << 16)  # read message history
    | (1 << 35)  # create public threads
    | (1 << 38)  # send messages in threads
)


def _ask(label: str, default: str | None = None) -> str:
    suffix = f" [{default}]" if default else ""
    value = input(f"{label}{suffix}: ").strip()
    return value or (default or "")


def _positive_id(value: str, label: str) -> int:
    try:
        result = int(value)
    except ValueError as exc:
        raise SystemExit(f"{label} must be a numeric Discord ID") from exc
    if result <= 0:
        raise SystemExit(f"{label} must be a positive Discord ID")
    return result


def _channel_slug(value: str) -> str:
    import re

    slug = re.sub(r"[^a-z0-9]+", "-", value.lower()).strip("-")
    return slug[:90] or "project"


def _toml_string(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def _write_private(path: Path, content: str) -> None:
    descriptor = os.open(path, os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o600)
    with os.fdopen(descriptor, "w", encoding="utf-8") as handle:
        handle.write(content)


def _write_config(
    path: Path,
    *,
    state_dir: Path,
    user_id: int,
    channel_id: int,
    guild_id: int,
    workspace: Path,
) -> None:
    content = f"""# Generated by `pam-discord setup`.
archive_dir = {_toml_string(str(state_dir / "archive"))}
instance_lock_dir = {_toml_string(str(state_dir / "instance.lock"))}
allowed_user_ids = [{user_id}]
max_attachment_mb = 25
max_audio_seconds = 1800
whisper_model = "small.en"
whisper_device = "cpu"
whisper_compute_type = "int8"
codex_binary = "codex"
codex_timeout_seconds = 1800

[channels.{_toml_string(str(channel_id))}]
workspace = {_toml_string(str(workspace))}
run_codex = true
instruction_prefix = "Follow this project's instructions."
project_record_dir = ".pam/conversations"

[guilds.{_toml_string(str(guild_id))}]
workspace = {_toml_string(str(workspace))}
run_codex = true
instruction_prefix = "Follow this project's instructions."
project_record_dir = ".pam/conversations"
"""
    _write_private(path, content)


def _configure_project_archive_git(workspace: Path, *, ignore: bool) -> None:
    path = workspace / ".gitignore"
    marker = ".pam/"
    if not ignore:
        if not path.exists():
            return
        lines = path.read_text(encoding="utf-8").splitlines()
        filtered = [line for line in lines if line.strip() != marker]
        if filtered != lines:
            content = "\n".join(filtered)
            path.write_text(f"{content}\n" if content else "", encoding="utf-8")
        return
    if path.exists():
        content = path.read_text(encoding="utf-8")
        if any(line.strip() == marker for line in content.splitlines()):
            return
        separator = "" if not content or content.endswith("\n") else "\n"
        path.write_text(f"{content}{separator}{marker}\n", encoding="utf-8")
    else:
        path.write_text(f"{marker}\n", encoding="utf-8")


def setup(argv: list[str] | None = None) -> None:
    parser = argparse.ArgumentParser(description="Guide one user through a first Pam workspace")
    parser.add_argument(
        "project", nargs="?", type=Path, help="Project directory for this Pam workspace"
    )
    parser.add_argument("--state-dir", type=Path)
    parser.add_argument("--workspace", type=Path, help=argparse.SUPPRESS)
    parser.add_argument("--user-id")
    parser.add_argument("--channel-id")
    parser.add_argument("--guild-id")
    parser.add_argument("--channel-name")
    parser.add_argument(
        "--no-service", action="store_true", help="Configure Pam without installing systemd"
    )
    history = parser.add_mutually_exclusive_group()
    history.add_argument(
        "--ignore-history", action="store_true", help="Add .pam conversation history to .gitignore"
    )
    history.add_argument(
        "--track-history", action="store_true", help="Allow .pam conversation history in Git"
    )
    args = parser.parse_args(argv)

    print("Pam setup\n")
    print(
        "Pam will run on this machine. Its private state stays in one data directory, while "
        "Codex works only in the project directory you approve.\n"
    )
    print(
        "Create a bot at https://discord.com/developers/applications and enable Message Content "
        "Intent. Pam will guide you through creating a dedicated project server and installing "
        "the bot there.\n"
        "In Discord, enable User Settings > Advanced > Developer Mode, then right-click your "
        "profile to copy your numeric user ID.\n"
    )
    state_dir = (
        args.state_dir
        or Path(_ask("Pam data directory", str(DEFAULT_STATE_DIR.expanduser())))
    ).expanduser().resolve()
    workspace_arg = args.project or args.workspace
    workspace = (
        workspace_arg or Path(_ask("Project directory", str(Path.cwd())))
    ).expanduser().resolve()
    if not workspace.is_dir():
        raise SystemExit(f"Project directory does not exist: {workspace}")

    state_dir.mkdir(parents=True, exist_ok=True)
    state_dir.chmod(stat.S_IRWXU)
    env_path = state_dir / ".env"
    config_path = state_dir / "config.toml"
    existing = [path for path in (env_path, config_path) if path.exists()]
    if existing:
        names = ", ".join(str(path) for path in existing)
        raise SystemExit(f"Setup stopped without overwriting existing files: {names}")

    user_id = _positive_id(
        str(args.user_id or _ask("Your Discord user ID")), "Discord user ID"
    )
    if args.ignore_history or args.track_history:
        ignore_history = args.ignore_history
    else:
        answer = _ask("Keep conversation history out of Git? (Y/n)", "Y").lower()
        if answer not in {"y", "yes", "n", "no"}:
            raise SystemExit("Please answer Y or n")
        ignore_history = answer in {"y", "yes"}
    token = getpass.getpass("Discord bot token (hidden): ").strip()
    if not token:
        raise SystemExit("Discord bot token is required")
    channel_id, guild_id, channel_url = _prepare_discord_workspace(
        token,
        workspace,
        channel_id=(
            _positive_id(str(args.channel_id), "Discord channel ID")
            if args.channel_id
            else None
        ),
        guild_id=(
            _positive_id(str(args.guild_id), "Discord server ID") if args.guild_id else None
        ),
        channel_name=args.channel_name,
    )

    _write_private(env_path, f"DISCORD_BOT_TOKEN={token}\n")
    try:
        _write_config(
            config_path,
            state_dir=state_dir,
            user_id=user_id,
            channel_id=channel_id,
            guild_id=guild_id,
            workspace=workspace,
        )
        _configure_project_archive_git(workspace, ignore=ignore_history)
    except Exception:
        env_path.unlink(missing_ok=True)
        raise

    print("\nWorkspace configured successfully.")
    print(f"  Pam data:  {state_dir}")
    print(f"  Project:   {workspace}")
    print(f"  Discord:   {channel_url}")
    print(f"  Server ID: {guild_id}")
    print(f"  Git:       conversation history {'ignored' if ignore_history else 'trackable'}")
    if args.no_service:
        print("\nPam is configured but not running. Start it with: pam-discord run")
        return

    from .service import install

    install(state_dir)
    print("\nPam is ready. Send a text or voice message here:")
    print(f"  {channel_url}")


def _check_codex(binary: str) -> tuple[bool, str]:
    resolved = shutil.which(binary)
    if resolved is None:
        return False, f"Codex executable not found: {binary}"
    result = subprocess.run(
        [resolved, "login", "status"],
        capture_output=True,
        text=True,
        timeout=20,
        check=False,
        env={key: value for key, value in os.environ.items() if key != "OPENAI_API_KEY"},
    )
    detail = (result.stdout or result.stderr).strip().splitlines()
    summary = detail[-1] if detail else "login status returned no details"
    return result.returncode == 0, summary


def _discord_request(
    token: str,
    path: str,
    *,
    method: str = "GET",
    payload: dict[str, object] | None = None,
) -> object:
    body = json.dumps(payload).encode("utf-8") if payload is not None else None
    request = urllib.request.Request(
        f"https://discord.com/api/v10{path}",
        data=body,
        method=method,
        headers={
            "Authorization": f"Bot {token}",
            "Content-Type": "application/json",
            "User-Agent": "PamDiscord/0.2",
        },
    )
    with urllib.request.urlopen(request, timeout=10) as response:
        return json.loads(response.read().decode("utf-8"))


def _discord_get(token: str, path: str) -> dict[str, object]:
    value = _discord_request(token, path)
    if not isinstance(value, dict):
        raise ValueError(f"Discord returned an unexpected response for {path}")
    return value


def _discord_install_url(client_id: str) -> str:
    query = urllib.parse.urlencode(
        {
            "client_id": client_id,
            "permissions": str(DISCORD_BOT_PERMISSIONS),
            "scope": "bot",
        }
    )
    return f"https://discord.com/oauth2/authorize?{query}"


def _select_guild(guilds: list[dict[str, object]], requested_id: int | None) -> dict[str, object]:
    if requested_id is not None:
        for guild in guilds:
            if str(guild.get("id")) == str(requested_id):
                return guild
        raise SystemExit(
            "Pam cannot see that Discord server. Open the installation link and add the bot first."
        )
    if not guilds:
        raise SystemExit("Pam cannot see a Discord server yet. Add the bot, then run setup again.")
    if len(guilds) == 1:
        return guilds[0]

    print("\nChoose the Discord server for this project:")
    for index, guild in enumerate(guilds, start=1):
        print(f"  {index}. {guild.get('name', guild.get('id'))}")
    choice = _ask("Server number")
    try:
        return guilds[int(choice) - 1]
    except (ValueError, IndexError) as exc:
        raise SystemExit("Invalid Discord server selection") from exc


def _prepare_discord_workspace(
    token: str,
    workspace: Path,
    *,
    channel_id: int | None,
    guild_id: int | None,
    channel_name: str | None,
) -> tuple[int, int, str]:
    try:
        bot_user = _discord_get(token, "/users/@me")
    except urllib.error.HTTPError as exc:
        if exc.code == 401:
            raise SystemExit("Discord rejected the bot token") from exc
        raise SystemExit(f"Discord API returned HTTP {exc.code}") from exc
    except (urllib.error.URLError, TimeoutError, ValueError) as exc:
        raise SystemExit(f"Could not connect to Discord: {exc}") from exc

    bot_id = str(bot_user.get("id") or "")
    if not bot_id:
        raise SystemExit("Discord did not return the bot application ID")

    if channel_id is not None:
        channel = _discord_get(token, f"/channels/{channel_id}")
        resolved_guild_id = _positive_id(str(channel.get("guild_id")), "Discord server ID")
        return channel_id, resolved_guild_id, (
            f"https://discord.com/channels/{resolved_guild_id}/{channel_id}"
        )

    print("\n1. Create a new Discord server for this project:")
    print("  https://discord.com/channels/@me")
    print(f"  In Discord, click +, choose Create My Own, and name it {workspace.name!r}.")
    if guild_id is None:
        input("\nPress Enter after the new server exists...")

    install_url = _discord_install_url(bot_id)
    print("\n2. Add Pam to that new server:")
    print(f"  {install_url}")
    if guild_id is None:
        input("\nPress Enter after Discord says Pam was added...")

    try:
        guild_value = _discord_request(token, "/users/@me/guilds")
    except urllib.error.HTTPError as exc:
        raise SystemExit(f"Could not list Pam's Discord servers (HTTP {exc.code})") from exc
    if not isinstance(guild_value, list):
        raise SystemExit("Discord returned an unexpected server list")
    guilds = [item for item in guild_value if isinstance(item, dict)]
    guild = _select_guild(guilds, guild_id)
    resolved_guild_id = _positive_id(str(guild.get("id")), "Discord server ID")

    name = _channel_slug(channel_name or "general")
    channels_value = _discord_request(token, f"/guilds/{resolved_guild_id}/channels")
    channels = channels_value if isinstance(channels_value, list) else []
    channel = next(
        (
            item
            for item in channels
            if isinstance(item, dict) and item.get("type") == 0 and item.get("name") == name
        ),
        None,
    )
    if channel is None:
        channel = _discord_request(
            token,
            f"/guilds/{resolved_guild_id}/channels",
            method="POST",
            payload={
                "name": name,
                "type": 0,
                "topic": f"Pam workspace for {workspace}",
            },
        )
    if not isinstance(channel, dict) or not channel.get("id"):
        raise SystemExit(f"Discord did not find or create #{name}")
    resolved_channel_id = _positive_id(str(channel["id"]), "Discord channel ID")
    channel_url = f"https://discord.com/channels/{resolved_guild_id}/{resolved_channel_id}"
    return resolved_channel_id, resolved_guild_id, channel_url


def _check_discord(
    token: str, channel_ids: list[int], guild_ids: list[int] | None = None
) -> tuple[bool, str]:
    try:
        bot_user = _discord_get(token, "/users/@me")
        bot_name = str(bot_user.get("username") or bot_user.get("id") or "bot")
        for channel_id in channel_ids:
            _discord_get(token, f"/channels/{channel_id}")
        for guild_id in guild_ids or []:
            _discord_get(token, f"/guilds/{guild_id}")
    except urllib.error.HTTPError as exc:
        if exc.code == 401:
            return False, "Discord rejected the bot token"
        if exc.code == 403:
            return False, "Discord bot cannot access a configured channel"
        if exc.code == 404:
            return False, "a configured Discord channel was not found"
        return False, f"Discord API returned HTTP {exc.code}"
    except (urllib.error.URLError, TimeoutError, ValueError) as exc:
        return False, f"could not reach Discord: {exc}"
    return True, (
        f"connected as {bot_name}; {len(guild_ids or [])} server(s) and "
        f"{len(channel_ids)} channel override(s) accessible"
    )


def doctor(argv: list[str] | None = None) -> None:
    parser = argparse.ArgumentParser(description="Check whether Pam is ready to run")
    parser.add_argument(
        "--state-dir", type=Path, default=DEFAULT_STATE_DIR, help="Pam data directory"
    )
    args = parser.parse_args(argv)
    state_dir = args.state_dir.expanduser().resolve()
    config_path = state_dir / "config.toml"
    env_path = state_dir / ".env"
    failures: list[str] = []

    try:
        config = load_config(config_path)
        print(f"OK  configuration: {config_path}")
        print(
            f"OK  workspace mappings: {len(config.guilds)} server(s), "
            f"{len(config.channels)} channel override(s)"
        )
    except Exception as exc:
        failures.append(f"configuration: {exc}")
        config = None

    secrets = dotenv_values(env_path) if env_path.exists() else {}
    token = secrets.get("DISCORD_BOT_TOKEN")
    if token and token != "replace-me":
        channel_ids = sorted(config.channels) if config else []
        guild_ids = sorted(config.guilds) if config else []
        discord_ok, discord_detail = _check_discord(str(token), channel_ids, guild_ids)
        if discord_ok:
            print(f"OK  Discord: {discord_detail}")
        else:
            failures.append(f"Discord: {discord_detail}")
    else:
        failures.append(f"Discord token: missing from {env_path}")

    binary = config.codex_binary if config else "codex"
    codex_ok, detail = _check_codex(binary)
    if codex_ok:
        print(f"OK  Codex: {detail}")
    else:
        failures.append(f"Codex: {detail}")

    if failures:
        for failure in failures:
            print(f"FAIL {failure}")
        raise SystemExit(1)
    print("\nPam is ready. Start it with:")
    if state_dir == DEFAULT_STATE_DIR.expanduser().resolve():
        print("pam-discord run")
    else:
        print(f"pam-discord run --env-file {env_path} --config {config_path}")
    print("After the interactive test works: pam-discord service install")
