from __future__ import annotations

import argparse
import getpass
import json
import os
import shutil
import stat
import subprocess
import urllib.error
import urllib.request
from pathlib import Path

from dotenv import dotenv_values

from .config import load_config

DEFAULT_STATE_DIR = Path("~/.local/share/pam-discord")


def _ask(label: str, default: str | None = None) -> str:
    suffix = f" [{default}]" if default else ""
    value = input(f"{label}{suffix}: ").strip()
    return value or (default or "")


def _positive_id(value: str, label: str) -> int:
    try:
        result = int(value)
    except ValueError as exc:
        raise SystemExit(f"{label} must be a numeric Discord ID") from exc
    if result <= 0:
        raise SystemExit(f"{label} must be a positive Discord ID")
    return result


def _toml_string(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def _write_private(path: Path, content: str) -> None:
    descriptor = os.open(path, os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o600)
    with os.fdopen(descriptor, "w", encoding="utf-8") as handle:
        handle.write(content)


def _write_config(
    path: Path,
    *,
    state_dir: Path,
    user_id: int,
    channel_id: int,
    workspace: Path,
) -> None:
    content = f"""# Generated by `pam-discord setup`.
archive_dir = {_toml_string(str(state_dir / "archive"))}
instance_lock_dir = {_toml_string(str(state_dir / "instance.lock"))}
allowed_user_ids = [{user_id}]
max_attachment_mb = 25
max_audio_seconds = 1800
whisper_model = "small.en"
whisper_device = "cpu"
whisper_compute_type = "int8"
codex_binary = "codex"
codex_timeout_seconds = 1800

[channels.{_toml_string(str(channel_id))}]
workspace = {_toml_string(str(workspace))}
run_codex = true
instruction_prefix = "Follow this project's instructions."
project_record_dir = "prompts/conversations"
"""
    _write_private(path, content)


def setup(argv: list[str] | None = None) -> None:
    parser = argparse.ArgumentParser(description="Guide one user through a first Pam workspace")
    parser.add_argument("--state-dir", type=Path)
    parser.add_argument("--workspace", type=Path)
    parser.add_argument("--user-id")
    parser.add_argument("--channel-id")
    args = parser.parse_args(argv)

    print("Pam setup\n")
    print(
        "Pam will run on this machine. Its private state stays in one data directory, while "
        "Codex works only in the project directory you approve.\n"
    )
    print(
        "Before continuing, create a bot at https://discord.com/developers/applications, "
        "enable Message Content Intent, and invite it to your Discord server.\n"
        "In Discord, enable User Settings > Advanced > Developer Mode. Then right-click your "
        "profile and project channel to copy their numeric IDs.\n"
    )
    state_dir = (
        args.state_dir
        or Path(_ask("Pam data directory", str(DEFAULT_STATE_DIR.expanduser())))
    ).expanduser().resolve()
    workspace = (
        args.workspace or Path(_ask("Project directory", str(Path.cwd())))
    ).expanduser().resolve()
    if not workspace.is_dir():
        raise SystemExit(f"Project directory does not exist: {workspace}")

    user_id = _positive_id(
        str(args.user_id or _ask("Your Discord user ID")), "Discord user ID"
    )
    channel_id = _positive_id(
        str(args.channel_id or _ask("Project Discord channel ID")), "Discord channel ID"
    )
    token = getpass.getpass("Discord bot token (hidden): ").strip()
    if not token:
        raise SystemExit("Discord bot token is required")

    state_dir.mkdir(parents=True, exist_ok=True)
    state_dir.chmod(stat.S_IRWXU)
    env_path = state_dir / ".env"
    config_path = state_dir / "config.toml"
    existing = [path for path in (env_path, config_path) if path.exists()]
    if existing:
        names = ", ".join(str(path) for path in existing)
        raise SystemExit(f"Setup stopped without overwriting existing files: {names}")

    _write_private(env_path, f"DISCORD_BOT_TOKEN={token}\n")
    try:
        _write_config(
            config_path,
            state_dir=state_dir,
            user_id=user_id,
            channel_id=channel_id,
            workspace=workspace,
        )
    except Exception:
        env_path.unlink(missing_ok=True)
        raise

    print("\nWorkspace configured successfully.")
    print(f"  Pam data:  {state_dir}")
    print(f"  Project:   {workspace}")
    print(f"  Config:    {config_path}")
    print("\nNext:")
    if state_dir == DEFAULT_STATE_DIR.expanduser().resolve():
        print("  pam-discord doctor")
        print("  pam-discord run")
    else:
        print(f"  pam-discord doctor --state-dir {_toml_string(str(state_dir))}")
        print(f"  pam-discord run --env-file {env_path} --config {config_path}")
    print("\nThen send a harmless test message in the mapped Discord channel.")


def _check_codex(binary: str) -> tuple[bool, str]:
    resolved = shutil.which(binary)
    if resolved is None:
        return False, f"Codex executable not found: {binary}"
    result = subprocess.run(
        [resolved, "login", "status"],
        capture_output=True,
        text=True,
        timeout=20,
        check=False,
        env={key: value for key, value in os.environ.items() if key != "OPENAI_API_KEY"},
    )
    detail = (result.stdout or result.stderr).strip().splitlines()
    summary = detail[-1] if detail else "login status returned no details"
    return result.returncode == 0, summary


def _discord_get(token: str, path: str) -> dict[str, object]:
    request = urllib.request.Request(
        f"https://discord.com/api/v10{path}",
        headers={"Authorization": f"Bot {token}", "User-Agent": "PamDiscord/0.2"},
    )
    with urllib.request.urlopen(request, timeout=10) as response:
        return json.loads(response.read().decode("utf-8"))


def _check_discord(token: str, channel_ids: list[int]) -> tuple[bool, str]:
    try:
        bot_user = _discord_get(token, "/users/@me")
        bot_name = str(bot_user.get("username") or bot_user.get("id") or "bot")
        for channel_id in channel_ids:
            _discord_get(token, f"/channels/{channel_id}")
    except urllib.error.HTTPError as exc:
        if exc.code == 401:
            return False, "Discord rejected the bot token"
        if exc.code == 403:
            return False, "Discord bot cannot access a configured channel"
        if exc.code == 404:
            return False, "a configured Discord channel was not found"
        return False, f"Discord API returned HTTP {exc.code}"
    except (urllib.error.URLError, TimeoutError, ValueError) as exc:
        return False, f"could not reach Discord: {exc}"
    return True, f"connected as {bot_name}; {len(channel_ids)} channel(s) accessible"


def doctor(argv: list[str] | None = None) -> None:
    parser = argparse.ArgumentParser(description="Check whether Pam is ready to run")
    parser.add_argument(
        "--state-dir", type=Path, default=DEFAULT_STATE_DIR, help="Pam data directory"
    )
    args = parser.parse_args(argv)
    state_dir = args.state_dir.expanduser().resolve()
    config_path = state_dir / "config.toml"
    env_path = state_dir / ".env"
    failures: list[str] = []

    try:
        config = load_config(config_path)
        print(f"OK  configuration: {config_path}")
        print(f"OK  workspace mappings: {len(config.channels)}")
    except Exception as exc:
        failures.append(f"configuration: {exc}")
        config = None

    secrets = dotenv_values(env_path) if env_path.exists() else {}
    token = secrets.get("DISCORD_BOT_TOKEN")
    if token and token != "replace-me":
        channel_ids = sorted(config.channels) if config else []
        discord_ok, discord_detail = _check_discord(str(token), channel_ids)
        if discord_ok:
            print(f"OK  Discord: {discord_detail}")
        else:
            failures.append(f"Discord: {discord_detail}")
    else:
        failures.append(f"Discord token: missing from {env_path}")

    binary = config.codex_binary if config else "codex"
    codex_ok, detail = _check_codex(binary)
    if codex_ok:
        print(f"OK  Codex: {detail}")
    else:
        failures.append(f"Codex: {detail}")

    if failures:
        for failure in failures:
            print(f"FAIL {failure}")
        raise SystemExit(1)
    print("\nPam is ready. Start it with:")
    if state_dir == DEFAULT_STATE_DIR.expanduser().resolve():
        print("pam-discord run")
    else:
        print(f"pam-discord run --env-file {env_path} --config {config_path}")
