from __future__ import annotations

import argparse
import ctypes
import getpass
import json
import os
import shutil
import stat
import subprocess
import sys
import urllib.error
import urllib.parse
import urllib.request
from pathlib import Path

from dotenv import dotenv_values

from .config import load_config

DEFAULT_STATE_DIR = Path("~/.local/share/pam-discord")
DISCORD_BOT_PERMISSIONS = (
    (1 << 4)  # manage channels
    | (1 << 10)  # view channels
    | (1 << 11)  # send messages
    | (1 << 16)  # read message history
    | (1 << 35)  # create public threads
    | (1 << 38)  # send messages in threads
)


def _whisper_defaults() -> tuple[str, str, str]:
    """Choose a fast transcription runtime that is usable, not merely advertised."""
    try:
        import ctranslate2

        if ctranslate2.get_cuda_device_count() < 1:
            raise RuntimeError("no CUDA device")
        ctypes.CDLL("libcublas.so.12")
        ctypes.CDLL("libcudnn_ops.so.9")
        return "distil-small.en", "cuda", "float16"
    except (ImportError, OSError, RuntimeError):
        return "tiny.en", "cpu", "int8"


def _ask(label: str, default: str | None = None) -> str:
    suffix = f" [{default}]" if default else ""
    value = input(f"{label}{suffix}: ").strip()
    return value or (default or "")


def _positive_id(value: str, label: str) -> int:
    try:
        result = int(value)
    except ValueError as exc:
        raise SystemExit(f"{label} must be a numeric Discord ID") from exc
    if result <= 0:
        raise SystemExit(f"{label} must be a positive Discord ID")
    return result


def _channel_slug(value: str) -> str:
    import re

    slug = re.sub(r"[^a-z0-9]+", "-", value.lower()).strip("-")
    return slug[:90] or "project"


def _toml_string(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def _write_private(path: Path, content: str) -> None:
    descriptor = os.open(path, os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o600)
    with os.fdopen(descriptor, "w", encoding="utf-8") as handle:
        handle.write(content)


def _write_config(
    path: Path,
    *,
    state_dir: Path,
    user_id: int,
    channel_id: int,
    guild_id: int,
    workspace: Path,
) -> None:
    whisper_model, whisper_device, whisper_compute_type = _whisper_defaults()
    content = f"""# Generated by `pam-discord setup`.
archive_dir = {_toml_string(str(state_dir / "archive"))}
instance_lock_dir = {_toml_string(str(state_dir / "instance.lock"))}
allowed_user_ids = [{user_id}]
max_attachment_mb = 25
max_audio_seconds = 1800
whisper_model = {_toml_string(whisper_model)}
whisper_device = {_toml_string(whisper_device)}
whisper_compute_type = {_toml_string(whisper_compute_type)}
whisper_beam_size = 1
codex_binary = "codex"
codex_timeout_seconds = 1800
codex_app_server_url = "ws://127.0.0.1:45832"
codex_full_access = true

[channels.{_toml_string(str(channel_id))}]
workspace = {_toml_string(str(workspace))}
run_codex = true
instruction_prefix = "Follow this project's instructions."
project_record_dir = ".pam/conversations"

[guilds.{_toml_string(str(guild_id))}]
workspace = {_toml_string(str(workspace))}
run_codex = true
instruction_prefix = "Follow this project's instructions."
project_record_dir = ".pam/conversations"
"""
    _write_private(path, content)


def _channel_config_block(
    channel_id: int,
    workspace: Path,
    *,
    project_root: Path | None = None,
) -> str:
    root_line = (
        f"project_root = {_toml_string(str(project_root))}\n"
        if project_root is not None and project_root != workspace
        else ""
    )
    return f"""

[channels.{_toml_string(str(channel_id))}]
workspace = {_toml_string(str(workspace))}
{root_line}run_codex = true
instruction_prefix = "Follow this project's instructions."
project_record_dir = ".pam/conversations"
"""


def _project_config_block(channel_id: int, guild_id: int, workspace: Path) -> str:
    return _channel_config_block(channel_id, workspace) + f"""
[guilds.{_toml_string(str(guild_id))}]
workspace = {_toml_string(str(workspace))}
run_codex = true
instruction_prefix = "Follow this project's instructions."
project_record_dir = ".pam/conversations"
"""


def _write_identity(state_dir: Path, user_id: int) -> None:
    path = state_dir / "identity.json"
    if not path.exists():
        _write_private(path, json.dumps({"discord_user_id": user_id}, indent=2) + "\n")


def _check_github_cli() -> tuple[bool, str]:
    binary = shutil.which("gh")
    if binary is None:
        return False, "not installed (optional)"
    try:
        status = subprocess.run(
            [binary, "auth", "status"],
            capture_output=True,
            text=True,
            timeout=20,
            check=False,
        )
    except (OSError, subprocess.TimeoutExpired):
        return False, "installed but status check failed (optional)"
    if status.returncode != 0:
        return False, "installed but not authenticated (optional)"
    try:
        account = subprocess.run(
            [binary, "api", "user", "--jq", ".login"],
            capture_output=True,
            text=True,
            timeout=20,
            check=False,
        )
    except (OSError, subprocess.TimeoutExpired):
        account = None
    login = account.stdout.strip() if account is not None and account.returncode == 0 else ""
    return True, f"authenticated{f' as {login}' if login else ''}"


def _configure_optional_developer_tools() -> None:
    github_ok, detail = _check_github_cli()
    if github_ok:
        print(f"GitHub CLI detected: {detail}")
        return
    if shutil.which("gh") is None:
        print("GitHub CLI not installed; skipping optional GitHub setup.")
        return
    if not sys.stdin.isatty():
        print(f"GitHub CLI: {detail}")
        return
    answer = _ask("Configure the optional GitHub CLI now? (y/N)", "N").lower()
    if answer not in {"y", "yes"}:
        return
    try:
        result = subprocess.run([str(shutil.which("gh")), "auth", "login"], check=False)
    except OSError:
        print("GitHub CLI login could not start. You can run `gh auth login` later.")
        return
    if result.returncode != 0:
        print("GitHub CLI login did not complete. You can run `gh auth login` later.")
        return
    github_ok, detail = _check_github_cli()
    print(f"GitHub CLI: {detail}")


def _setup_identity(args: argparse.Namespace) -> None:
    state_dir = (
        args.state_dir
        or Path(_ask("pam data directory", str(DEFAULT_STATE_DIR.expanduser())))
    ).expanduser().resolve()
    state_dir.mkdir(parents=True, exist_ok=True)
    state_dir.chmod(stat.S_IRWXU)
    env_path = state_dir / ".env"
    identity_path = state_dir / "identity.json"
    if env_path.exists() or identity_path.exists():
        raise SystemExit("pam is already set up. Add a project with `./pam project add PATH`.")
    user_id = _positive_id(
        str(args.user_id or _ask("Your Discord user ID")), "Discord user ID"
    )
    token = getpass.getpass("Discord bot token (hidden): ").strip()
    if not token:
        raise SystemExit("Discord bot token is required")
    _write_private(env_path, f"DISCORD_BOT_TOKEN={token}\n")
    _write_identity(state_dir, user_id)
    _configure_optional_developer_tools()
    print("\npam identity saved. Connect a project with:")
    print("  ./pam project add /path/to/project")


def _configure_project_archive_git(workspace: Path, *, ignore: bool) -> None:
    path = workspace / ".gitignore"
    marker = ".pam/"
    if not ignore:
        if not path.exists():
            return
        lines = path.read_text(encoding="utf-8").splitlines()
        filtered = [line for line in lines if line.strip() != marker]
        if filtered != lines:
            content = "\n".join(filtered)
            path.write_text(f"{content}\n" if content else "", encoding="utf-8")
        return
    if path.exists():
        content = path.read_text(encoding="utf-8")
        if any(line.strip() == marker for line in content.splitlines()):
            return
        separator = "" if not content or content.endswith("\n") else "\n"
        path.write_text(f"{content}{separator}{marker}\n", encoding="utf-8")
    else:
        path.write_text(f"{marker}\n", encoding="utf-8")


def setup(argv: list[str] | None = None) -> None:
    parser = argparse.ArgumentParser(description="Guide one user through a first pam workspace")
    parser.add_argument(
        "project", nargs="?", type=Path, help="Project directory for this pam workspace"
    )
    parser.add_argument("--state-dir", type=Path)
    parser.add_argument("--workspace", type=Path, help=argparse.SUPPRESS)
    parser.add_argument("--user-id")
    parser.add_argument("--channel-id")
    parser.add_argument("--guild-id")
    parser.add_argument("--channel-name")
    parser.add_argument(
        "--no-service", action="store_true", help="Configure pam without installing systemd"
    )
    history = parser.add_mutually_exclusive_group()
    history.add_argument(
        "--ignore-history", action="store_true", help="Add .pam conversation history to .gitignore"
    )
    history.add_argument(
        "--track-history", action="store_true", help="Allow .pam conversation history in Git"
    )
    args = parser.parse_args(argv)

    if args.project is None and args.workspace is None:
        _setup_identity(args)
        return

    print("pam setup\n")
    print(
        "pam will run on this machine. Its private state stays in one data directory, while "
        "Codex works only in the project directory you approve.\n"
    )
    print(
        "Create a bot at https://discord.com/developers/applications and enable Message Content "
        "Intent. pam will guide you through creating a dedicated project server and installing "
        "the bot there.\n"
        "In Discord, enable User Settings > Advanced > Developer Mode, then right-click your "
        "profile to copy your numeric user ID.\n"
    )
    state_dir = (
        args.state_dir
        or Path(_ask("pam data directory", str(DEFAULT_STATE_DIR.expanduser())))
    ).expanduser().resolve()
    workspace_arg = args.project or args.workspace
    workspace = (
        workspace_arg or Path(_ask("Project directory", str(Path.cwd())))
    ).expanduser().resolve()
    if not workspace.is_dir():
        raise SystemExit(f"Project directory does not exist: {workspace}")

    state_dir.mkdir(parents=True, exist_ok=True)
    state_dir.chmod(stat.S_IRWXU)
    env_path = state_dir / ".env"
    config_path = state_dir / "config.toml"
    existing = [path for path in (env_path, config_path) if path.exists()]
    if existing:
        names = ", ".join(str(path) for path in existing)
        raise SystemExit(f"Setup stopped without overwriting existing files: {names}")

    user_id = _positive_id(
        str(args.user_id or _ask("Your Discord user ID")), "Discord user ID"
    )
    if args.ignore_history or args.track_history:
        ignore_history = args.ignore_history
    else:
        answer = _ask("Keep conversation history out of Git? (Y/n)", "Y").lower()
        if answer not in {"y", "yes", "n", "no"}:
            raise SystemExit("Please answer Y or n")
        ignore_history = answer in {"y", "yes"}
    token = getpass.getpass("Discord bot token (hidden): ").strip()
    if not token:
        raise SystemExit("Discord bot token is required")
    channel_id, guild_id, channel_url = _prepare_discord_workspace(
        token,
        workspace,
        channel_id=(
            _positive_id(str(args.channel_id), "Discord channel ID")
            if args.channel_id
            else None
        ),
        guild_id=(
            _positive_id(str(args.guild_id), "Discord server ID") if args.guild_id else None
        ),
        channel_name=args.channel_name,
    )

    _write_private(env_path, f"DISCORD_BOT_TOKEN={token}\n")
    _write_identity(state_dir, user_id)
    try:
        _write_config(
            config_path,
            state_dir=state_dir,
            user_id=user_id,
            channel_id=channel_id,
            guild_id=guild_id,
            workspace=workspace,
        )
        _configure_project_archive_git(workspace, ignore=ignore_history)
    except Exception:
        env_path.unlink(missing_ok=True)
        raise

    print("\nWorkspace configured successfully.")
    print(f"  pam data:  {state_dir}")
    print(f"  Project:   {workspace}")
    print(f"  Discord:   {channel_url}")
    print(f"  Server ID: {guild_id}")
    print(f"  Git:       conversation history {'ignored' if ignore_history else 'trackable'}")
    if args.no_service:
        print("\npam is configured but not running. Start it with: pam-discord run")
        return

    from .service import install

    install(state_dir)
    print("\npam is ready. Send a text or voice message here:")
    print(f"  {channel_url}")


def project_add(
    argv: list[str] | None = None,
    *,
    create: bool = False,
) -> None:
    parser = argparse.ArgumentParser(
        description=(
            "Create and connect a new project to pam"
            if create
            else "Connect another project to pam"
        )
    )
    parser.add_argument("project", type=Path)
    parser.add_argument("--state-dir", type=Path, default=DEFAULT_STATE_DIR)
    history = parser.add_mutually_exclusive_group()
    history.add_argument("--ignore-history", action="store_true")
    history.add_argument("--track-history", action="store_true")
    parser.add_argument("--no-service", action="store_true")
    args = parser.parse_args(argv)
    state_dir = args.state_dir.expanduser().resolve()
    identity_path = state_dir / "identity.json"
    env_path = state_dir / ".env"
    if not identity_path.exists() or not env_path.exists():
        raise SystemExit("Run `./pam setup` once before adding a project.")
    identity = json.loads(identity_path.read_text(encoding="utf-8"))
    user_id = _positive_id(str(identity["discord_user_id"]), "Discord user ID")
    token = str(dotenv_values(env_path).get("DISCORD_BOT_TOKEN") or "")
    if not token:
        raise SystemExit("Discord bot token is missing")
    workspace = args.project.expanduser().resolve()
    if create:
        if workspace.exists():
            raise SystemExit(
                f"Project path already exists: {workspace}\n"
                "Use `pam project add PATH` to connect it."
            )
        if not workspace.parent.is_dir():
            raise SystemExit(f"Parent directory does not exist: {workspace.parent}")
        workspace.mkdir()
    elif not workspace.is_dir():
        raise SystemExit(f"Project directory does not exist: {workspace}")
    config_path = state_dir / "config.toml"
    if config_path.exists():
        existing = load_config(config_path)
        if any(item.workspace == workspace for item in existing.guilds.values()):
            raise SystemExit(f"Project is already connected: {workspace}")
    if args.ignore_history or args.track_history:
        ignore_history = args.ignore_history
    else:
        answer = _ask("Keep conversation history out of Git? (Y/n)", "Y").lower()
        if answer not in {"y", "yes", "n", "no"}:
            raise SystemExit("Please answer Y or n")
        ignore_history = answer in {"y", "yes"}
    channel_id, guild_id, channel_url = _prepare_discord_workspace(
        token, workspace, channel_id=None, guild_id=None, channel_name=None
    )
    if config_path.exists():
        with config_path.open("a", encoding="utf-8") as handle:
            handle.write(_project_config_block(channel_id, guild_id, workspace))
    else:
        _write_config(
            config_path,
            state_dir=state_dir,
            user_id=user_id,
            channel_id=channel_id,
            guild_id=guild_id,
            workspace=workspace,
        )
    _configure_project_archive_git(workspace, ignore=ignore_history)
    print(f"\nProject connected: {workspace}")
    print(f"Discord: {channel_url}")
    if args.no_service:
        return
    from .service import install, restart

    if len(load_config(config_path).guilds) == 1:
        install(state_dir)
    else:
        restart(state_dir)


def _check_codex(binary: str) -> tuple[bool, str]:
    resolved = shutil.which(binary)
    if resolved is None:
        return False, f"Codex executable not found: {binary}"
    result = subprocess.run(
        [resolved, "login", "status"],
        capture_output=True,
        text=True,
        timeout=20,
        check=False,
        env={key: value for key, value in os.environ.items() if key != "OPENAI_API_KEY"},
    )
    detail = (result.stdout or result.stderr).strip().splitlines()
    summary = detail[-1] if detail else "login status returned no details"
    return result.returncode == 0, summary


def _discord_request(
    token: str,
    path: str,
    *,
    method: str = "GET",
    payload: dict[str, object] | None = None,
) -> object:
    body = json.dumps(payload).encode("utf-8") if payload is not None else None
    request = urllib.request.Request(
        f"https://discord.com/api/v10{path}",
        data=body,
        method=method,
        headers={
            "Authorization": f"Bot {token}",
            "Content-Type": "application/json",
            "User-Agent": "pamDiscord/0.2",
        },
    )
    with urllib.request.urlopen(request, timeout=10) as response:
        return json.loads(response.read().decode("utf-8"))


def _discord_get(token: str, path: str) -> dict[str, object]:
    value = _discord_request(token, path)
    if not isinstance(value, dict):
        raise ValueError(f"Discord returned an unexpected response for {path}")
    return value


def _discord_install_url(client_id: str) -> str:
    query = urllib.parse.urlencode(
        {
            "client_id": client_id,
            "permissions": str(DISCORD_BOT_PERMISSIONS),
            "scope": "bot",
        }
    )
    return f"https://discord.com/oauth2/authorize?{query}"


def _select_guild(guilds: list[dict[str, object]], requested_id: int | None) -> dict[str, object]:
    if requested_id is not None:
        for guild in guilds:
            if str(guild.get("id")) == str(requested_id):
                return guild
        raise SystemExit(
            "pam cannot see that Discord server. Open the installation link and add the bot first."
        )
    if not guilds:
        raise SystemExit("pam cannot see a Discord server yet. Add the bot, then run setup again.")
    if len(guilds) == 1:
        return guilds[0]

    print("\nChoose the Discord server for this project:")
    for index, guild in enumerate(guilds, start=1):
        print(f"  {index}. {guild.get('name', guild.get('id'))}")
    choice = _ask("Server number")
    try:
        return guilds[int(choice) - 1]
    except (ValueError, IndexError) as exc:
        raise SystemExit("Invalid Discord server selection") from exc


def _prepare_discord_workspace(
    token: str,
    workspace: Path,
    *,
    channel_id: int | None,
    guild_id: int | None,
    channel_name: str | None,
) -> tuple[int, int, str]:
    try:
        bot_user = _discord_get(token, "/users/@me")
    except urllib.error.HTTPError as exc:
        if exc.code == 401:
            raise SystemExit("Discord rejected the bot token") from exc
        raise SystemExit(f"Discord API returned HTTP {exc.code}") from exc
    except (urllib.error.URLError, TimeoutError, ValueError) as exc:
        raise SystemExit(f"Could not connect to Discord: {exc}") from exc

    bot_id = str(bot_user.get("id") or "")
    if not bot_id:
        raise SystemExit("Discord did not return the bot application ID")

    if channel_id is not None:
        channel = _discord_get(token, f"/channels/{channel_id}")
        resolved_guild_id = _positive_id(str(channel.get("guild_id")), "Discord server ID")
        _discord_request(
            token,
            f"/guilds/{resolved_guild_id}/members/@me",
            method="PATCH",
            payload={"nick": "pam"},
        )
        return channel_id, resolved_guild_id, (
            f"https://discord.com/channels/{resolved_guild_id}/{channel_id}"
        )

    print("\n1. Create a new Discord server for this project:")
    print("  https://discord.com/channels/@me")
    print(f"  In Discord, click +, choose Create My Own, and name it {workspace.name!r}.")
    if guild_id is None:
        input("\nPress Enter after the new server exists...")

    install_url = _discord_install_url(bot_id)
    print("\n2. Add pam to that new server:")
    print(f"  {install_url}")
    if guild_id is None:
        input("\nPress Enter after Discord says pam was added...")

    try:
        guild_value = _discord_request(token, "/users/@me/guilds")
    except urllib.error.HTTPError as exc:
        raise SystemExit(f"Could not list pam's Discord servers (HTTP {exc.code})") from exc
    if not isinstance(guild_value, list):
        raise SystemExit("Discord returned an unexpected server list")
    guilds = [item for item in guild_value if isinstance(item, dict)]
    guild = _select_guild(guilds, guild_id)
    resolved_guild_id = _positive_id(str(guild.get("id")), "Discord server ID")
    _discord_request(
        token,
        f"/guilds/{resolved_guild_id}/members/@me",
        method="PATCH",
        payload={"nick": "pam"},
    )

    name = _channel_slug(channel_name or "general")
    channels_value = _discord_request(token, f"/guilds/{resolved_guild_id}/channels")
    channels = channels_value if isinstance(channels_value, list) else []
    channel = next(
        (
            item
            for item in channels
            if isinstance(item, dict) and item.get("type") == 0 and item.get("name") == name
        ),
        None,
    )
    if channel is None:
        channel = _discord_request(
            token,
            f"/guilds/{resolved_guild_id}/channels",
            method="POST",
            payload={
                "name": name,
                "type": 0,
                "topic": f"pam workspace for {workspace}",
            },
        )
    if not isinstance(channel, dict) or not channel.get("id"):
        raise SystemExit(f"Discord did not find or create #{name}")
    resolved_channel_id = _positive_id(str(channel["id"]), "Discord channel ID")
    channel_url = f"https://discord.com/channels/{resolved_guild_id}/{resolved_channel_id}"
    return resolved_channel_id, resolved_guild_id, channel_url


def _check_discord(
    token: str, channel_ids: list[int], guild_ids: list[int] | None = None
) -> tuple[bool, str]:
    try:
        bot_user = _discord_get(token, "/users/@me")
        bot_name = str(bot_user.get("username") or bot_user.get("id") or "bot")
        for channel_id in channel_ids:
            _discord_get(token, f"/channels/{channel_id}")
        for guild_id in guild_ids or []:
            _discord_get(token, f"/guilds/{guild_id}")
    except urllib.error.HTTPError as exc:
        if exc.code == 401:
            return False, "Discord rejected the bot token"
        if exc.code == 403:
            return False, "Discord bot cannot access a configured channel"
        if exc.code == 404:
            return False, "a configured Discord channel was not found"
        return False, f"Discord API returned HTTP {exc.code}"
    except (urllib.error.URLError, TimeoutError, ValueError) as exc:
        return False, f"could not reach Discord: {exc}"
    return True, (
        f"connected as {bot_name}; {len(guild_ids or [])} server(s) and "
        f"{len(channel_ids)} channel override(s) accessible"
    )


def doctor(argv: list[str] | None = None) -> None:
    parser = argparse.ArgumentParser(description="Check whether pam is ready to run")
    parser.add_argument(
        "--state-dir", type=Path, default=DEFAULT_STATE_DIR, help="pam data directory"
    )
    args = parser.parse_args(argv)
    state_dir = args.state_dir.expanduser().resolve()
    config_path = state_dir / "config.toml"
    env_path = state_dir / ".env"
    failures: list[str] = []

    try:
        config = load_config(config_path)
        print(f"OK  configuration: {config_path}")
        print(
            f"OK  workspace mappings: {len(config.guilds)} server(s), "
            f"{len(config.channels)} channel override(s)"
        )
        print(
            f"OK  transcription: {config.whisper_model} on {config.whisper_device} "
            f"({config.whisper_compute_type}, beam {config.whisper_beam_size})"
        )
    except Exception as exc:
        failures.append(f"configuration: {exc}")
        config = None

    secrets = dotenv_values(env_path) if env_path.exists() else {}
    token = secrets.get("DISCORD_BOT_TOKEN")
    if token and token != "replace-me":
        channel_ids = sorted(config.channels) if config else []
        guild_ids = sorted(config.guilds) if config else []
        discord_ok, discord_detail = _check_discord(str(token), channel_ids, guild_ids)
        if discord_ok:
            print(f"OK  Discord: {discord_detail}")
        else:
            failures.append(f"Discord: {discord_detail}")
    else:
        failures.append(f"Discord token: missing from {env_path}")

    binary = config.codex_binary if config else "codex"
    codex_ok, detail = _check_codex(binary)
    if codex_ok:
        print(f"OK  Codex: {detail}")
    else:
        failures.append(f"Codex: {detail}")

    github_ok, github_detail = _check_github_cli()
    prefix = "OK  " if github_ok else "INFO"
    print(f"{prefix} GitHub CLI: {github_detail}")

    if failures:
        for failure in failures:
            print(f"FAIL {failure}")
        raise SystemExit(1)
    print("\npam is ready. Start it with:")
    if state_dir == DEFAULT_STATE_DIR.expanduser().resolve():
        print("pam-discord run")
    else:
        print(f"pam-discord run --env-file {env_path} --config {config_path}")
    print("After the interactive test works: pam-discord service install")
